services:
  frontend:
    image: aksharshare/makereelsv2-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://makereels.live
    depends_on:
      - backend
    networks:
      - makereels-network
    restart: unless-stopped
    command: node .next/standalone/server.js

  backend:
    image: aksharshare/makereelsv2-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - ./automationtool/input:/app/input
      - ./automationtool/output:/app/output
      - ./automationtool/config:/app/config
    networks:
      - makereels-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/makereels/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/nginx/ssl:/etc/nginx/ssl:ro
      - /root/makereels/nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - makereels-network
    restart: unless-stopped

# certbot:
#   image: certbot/certbot
#   volumes:
#     - /root/nginx/ssl:/etc/letsencrypt
#     - ./nginx/webroot:/var/www/certbot
#   command: certonly --webroot --webroot-path=/var/www/certbot --email admin@makereels.live --agree-tos --no-eff-email -d makereels.live -d www.makereels.live
#   networks:
#     - makereels-network

networks:
  makereels-network:
    driver: bridge


